name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*.md'
    branches: [master]
  pull_request:
    paths-ignore:
      - '**/*.md'
    branches: [master]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-lib:
    name: Build ${{ matrix.module }}
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - ":nav3ksp"
          - ":ksp:nav3ksp-annotation"
          - ":ksp:nav3ksp-processor"
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup build env
        uses: ./.github/actions/build-env

      - name: Assemble
        run: gradle ${{ matrix.module }}:assemble --no-daemon

  build-example-apk:
    name: Build example app (APK)
    needs: build-lib
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup build env
        uses: ./.github/actions/build-env

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Assemble
        run: gradle :example:composeApp:assembleDebug --no-daemon

      - name: Collect Artifacts
        env:
          APP_BUILD_PATH: "example/composeApp/build"
        run: |
          mkdir -p artifacts/android
          cp -r $APP_BUILD_PATH/outputs/apk/debug/*.apk artifacts/android/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: android-build
          path: artifacts/android
          retention-days: 14
