name: Maven Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"
      - "*.*.*-*"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  maven_publish:
    name: Publish release
    runs-on: macOS-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup build env
        uses: ./.github/actions/build-env

      - name: Publish
        run: gradle publishToMavenCentral --no-configuration-cache --no-daemon
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}

      - name: Determine prerelease
        id: release_meta
        run: |
          if [[ "${GITHUB_REF_NAME}" == *-* ]]; then
            echo "prerelease=true" >> "$GITHUB_OUTPUT"
            echo "draft=false" >> "$GITHUB_OUTPUT"
          else
            echo "prerelease=false" >> "$GITHUB_OUTPUT"
            echo "draft=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: ${{ steps.release_type.outputs.prerelease }}
          draft: ${{ steps.release_type.outputs.draft }}