name: Maven Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"
      - "*.*.*-*"

permissions:
  contents: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  maven_publish:
    name: Publish release
    runs-on: macOS-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup build env
        uses: ./.github/actions/build-env

      - name: Publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS_B64 }}
        run: gradle publishAndReleaseToMavenCentral --no-configuration-cache --no-daemon

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: v${{ github.ref_name }}
          prerelease: ${{ contains(github.ref_name, '-') }}
          generate_release_notes: true
          draft: false
